# Generated by Django 3.1 on 2020-08-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='listaComentario',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
    ]
