# Generated by Django 3.1 on 2020-08-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_remove_comentario_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='resenha',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
