# Generated by Django 3.1 on 2020-08-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='comentarioAvaliacao',
        ),
    ]
