# Generated by Django 3.1 on 2020-08-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_avaliacao_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='comentario',
        ),
    ]
